export const REGISTER_USER_REQUEST = 'REGISTER_USER_REQUEST'
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS'
export const REGISTER_USER_FAIL = 'REGISTER_USER_FAIL'

export const LOGIN_USER_REQUEST = 'LOGIN_USER_REQUEST'
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS'
export const LOGIN_USER_FAIL = 'LOGIN_USER_FAIL'

export const USER_LOGOUT = 'USER_LOGOUT'

export const EDIT_PROFILE_REQUEST = 'EDIT_PROFILE_REQUEST'
export const EDIT_PROFILE_SUCCESS = 'EDIT_PROFILE_SUCCESS'
export const EDIT_PROFILE_FAIL = 'EDIT_PROFILE_FAIL'
export const EDIT_PROFILE_RESET = 'EDIT_PROFILE_RESET'

export const FOLLOW_PROFILE_REQUEST = 'FOLLOW_PROFILE_REQUEST'
export const FOLLOW_PROFILE_SUCCESS = 'FOLLOW_PROFILE_SUCCESS'
export const FOLLOW_PROFILE_FAIL = 'FOLLOW_PROFILE_FAIL'

export const LIST_POSTS_REQUEST = 'LIST_POSTS_REQUEST'
export const LIST_POSTS_SUCCESS = 'LIST_POSTS_SUCCESS'
export const LIST_POSTS_FAIL = 'LIST_POSTS_FAIL'
export const LIST_POSTS_RESET = 'LIST_POSTS_RESET'

export const CREATE_POST_REQUEST = 'CREATE_POST_REQUEST'
export const CREATE_POST_SUCCESS = 'CREATE_POST_SUCCESS'
export const CREATE_POST_FAIL = 'CREATE_POST_FAIL'

export const REMOVE_POST_REQUEST = 'REMOVE_POST_REQUEST'
export const REMOVE_POST_SUCCESS = 'REMOVE_POST_SUCCESS'
export const REMOVE_POST_FAIL = 'REMOVE_POST_FAIL'

export const LIST_USERS_REQUEST = 'LIST_USERS_REQUEST'
export const LIST_USERS_SUCCESS = 'LIST_USERS_SUCCESS'
export const LIST_USERS_FAIL = 'LIST_USERS_FAIL'
export const LIST_USERS_RESET = 'LIST_USERS_RESET'

export const DETAILS_USER_REQUEST = 'DETAILS_USER_REQUEST'
export const DETAILS_USER_SUCCESS = 'DETAILS_USER_SUCCESS'
export const DETAILS_USER_FAIL = 'DETAILS_USER_FAIL'
export const DETAILS_USER_RESET = 'DETAILS_USER_RESET'

export const CREATE_COMMENT_REQUEST = 'CREATE_COMMENT_REQUEST'
export const CREATE_COMMENT_SUCCESS = 'CREATE_COMMENT_SUCCESS'
export const CREATE_COMMENT_FAIL = 'CREATE_COMMENT_FAIL'

export const REMOVE_COMMENT_REQUEST = 'REMOVE_COMMENT_REQUEST'
export const REMOVE_COMMENT_SUCCESS = 'REMOVE_COMMENT_SUCCESS'
export const REMOVE_COMMENT_FAIL = 'REMOVE_COMMENT_FAIL'

export const CREATE_LIKE_REQUEST = 'CREATE_LIKE_REQUEST'
export const CREATE_LIKE_SUCCESS = 'CREATE_LIKE_SUCCESS'
export const CREATE_LIKE_FAIL = 'CREATE_LIKE_FAIL'

export const REMOVE_LIKE_REQUEST = 'REMOVE_LIKE_REQUEST'
export const REMOVE_LIKE_SUCCESS = 'REMOVE_LIKE_SUCCESS'
export const REMOVE_LIKE_FAIL = 'REMOVE_LIKE_FAIL'